import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CheckCircle2, FileText, ShieldCheck } from "lucide-react";
import { getConsentBySlug } from "@/lib/queries/consent";
import { ConsentForm } from "./consent-form";

export const metadata: Metadata = { title: "Consultation Consent" };

export default async function ConsentPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const consent = await getConsentBySlug(slug);
  if (!consent) notFound();

  const decided = consent.isAccepted || consent.isRejected;

  return (
    <section className="flex min-h-screen items-center justify-center bg-gradient-to-br from-brand-50 via-accent-50/40 to-brand-50 px-5 py-24">
      <div className="w-full max-w-lg">
        <div className="rounded-3xl border border-brand-900/10 bg-white p-8 shadow-float">
          <div className="flex items-center gap-3">
            <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-brand-700 to-accent-600 text-white">
              <ShieldCheck className="h-6 w-6" />
            </div>
            <div>
              <h1 className="font-display text-xl font-extrabold text-ink">
                {decided ? "Response recorded" : "Consultation consent"}
              </h1>
              <p className="text-sm text-ink-muted">
                {decided ? "Thank you for responding." : "Please review and respond below."}
              </p>
            </div>
          </div>

          <div className="mt-7 space-y-4 rounded-2xl bg-surface p-5 text-sm">
            <div className="flex items-center justify-between">
              <span className="text-ink-muted">Doctor</span>
              <span className="font-semibold text-ink">{consent.doctorName}</span>
            </div>
            {consent.doctorQualification && (
              <div className="flex items-center justify-between">
                <span className="text-ink-muted">Qualification</span>
                <span className="font-semibold text-ink">{consent.doctorQualification}</span>
              </div>
            )}
            <div className="flex items-center justify-between">
              <span className="text-ink-muted">Patient</span>
              <span className="font-semibold text-ink">{consent.patientName}</span>
            </div>
            {consent.appointmentDate && (
              <div className="flex items-center justify-between">
                <span className="text-ink-muted">Appointment</span>
                <span className="font-semibold text-ink">
                  {new Date(consent.appointmentDate).toLocaleDateString("en-IN", {
                    day: "numeric",
                    month: "long",
                    year: "numeric",
                  })}
                  {consent.appointmentTime ? ` at ${consent.appointmentTime}` : ""}
                </span>
              </div>
            )}
          </div>

          <p className="mt-6 text-sm leading-relaxed text-ink-muted">
            I understand and consent to the medical consultation with the doctor named above,
            including any recommended examinations, diagnostic tests and treatments. I confirm
            that the information I have provided is accurate to the best of my knowledge.
          </p>

          {decided ? (
            <div className="mt-7 rounded-2xl border border-accent-500/30 bg-accent-50 p-6 text-center">
              <CheckCircle2 className="mx-auto h-10 w-10 text-accent-600" />
              <p className="mt-3 font-semibold text-ink">
                {consent.isAccepted ? "Consent accepted" : "Consent declined"}
              </p>
              <p className="mt-1 text-sm text-ink-muted">
                {consent.isAccepted
                  ? "The clinic has been notified of your acceptance."
                  : "The clinic has been notified of your decision."}
              </p>
              {consent.consentFile && (
                <a
                  href={`/api/consents/${consent.slug}/file`}
                  target="_blank"
                  rel="noreferrer"
                  className="mt-4 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-2.5 text-sm font-semibold text-brand-700 shadow-sm ring-1 ring-brand-200 transition-colors hover:bg-brand-50"
                >
                  <FileText className="h-4 w-4" />
                  {consent.consentFile.startsWith("consent-pdfs/")
                    ? "Download consent certificate"
                    : "Download uploaded document"}
                </a>
              )}
            </div>
          ) : (
            <ConsentForm slug={consent.slug} />
          )}
        </div>

        <p className="mt-6 text-center text-xs text-ink-muted">
          Secured by SkoraCares · This request was generated by your healthcare provider.
        </p>
      </div>
    </section>
  );
}
