<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\MedicineMaster;

class MedicineSeeder extends Seeder
{
    public function run(): void
    {
        $medicineMaster = [
            'Hapiron XT Tablet',
            'Dilcor 60mg Tablet',
            'Pruderm Cream',
            'Nozcalm-RS Respules (4ml Each)',
            'Zelacid 20 Tablet',
            'Cilian-M 10/50 Tablet ER',
            'Pirasan 200mg Injection',
            'Opilox 500 Tablet',
            'Lilica Zole Cream',
            'Acloy TH 60mg/4mg Tablet',
            'Uripay 100mg Tablet',
            'Benpro 40mg Tablet',
            'Rabecon D 30 mg/20 mg Capsule',
            'Reebo D 30mg/20mg Capsule SR',
            'Gee-X Pain Relieving Gel',
            'Presolone-M8 Tablet',
            'Lecope-M Tablet',
            'Jeopride 200mg Tablet',
            'Etorlin Tablet',
            'Voglitor MD 0.3 Tablet',
            'Sylox-OZ Tablet',
            'Laxoford Oral Solution Lemon',
            'Hexagab NT 75mg/10mg Tablet',
            'PETOGEN 150 MG INJECTION',
            'Nudol 100mg/500mg Tablet',
            'Clovis-L Ear Drop',
            'NDX 25mg Injection',
            'Enzoflam TP 37.5mg/325mg Tablet',
            'Zdcort 6mg Tablet',
            'Roxitral 150 Tablet',
            'Miconex 500mcg Injection',
            'Temperate DS 250mg Oral Suspension',
            'Kufhil-LS Syrup',
            'Showcef 250mg Tablet',
            'Rabenes-DSR 30mg/20mg Capsule',
            'Pirfetid 200mg Tablet',
            'Naproxia-D Tablet',
            'Albimol MF Suspension',
            'Nuphos 200 Injection',
            'Skinshine Cream',
            'Stancef 500mg Injection',
            'Bactspan 200mg Tablet',
            'Rosidon-F Tablet',
            'Symbol 60mg Tablet',
            'Rorace 20mg Tablet',
            'ValeNt 80 Tablet',
            'Icopan 40 Tablet',
            'Nacsia-AQ Injection',
            'F Cure 75mg Injection',
            'Onditron 2mg Injection',
            'Paracetamol 500mg Tablet',
            'Azithromycin 500mg Tablet',
            'Amoxicillin 500mg Capsule',
            'Cefixime 200mg Tablet',
            'Cetirizine 10mg Tablet',
            'Montelukast 10mg Tablet',
            'Pantoprazole 40mg Tablet',
            'Rabeprazole 20mg Tablet',
            'Domperidone 10mg Tablet',
            'Ondansetron 4mg Tablet',
            'Ibuprofen 400mg Tablet',
            'Diclofenac 50mg Tablet',
            'Nimesulide 100mg Tablet',
            'Aceclofenac 100mg Tablet',
            'Metformin 500mg Tablet',
            'Glimepiride 1mg Tablet',
            'Insulin Injection',
            'Amlodipine 5mg Tablet',
            'Atenolol 50mg Tablet',
            'Losartan 50mg Tablet',
            'Telmisartan 40mg Tablet',
            'Hydrochlorothiazide Tablet',
            'Furosemide 40mg Tablet',
            'Spironolactone Tablet',
            'Atorvastatin 10mg Tablet',
            'Rosuvastatin 10mg Tablet',
            'Clopidogrel 75mg Tablet',
            'Aspirin 75mg Tablet',
            'Warfarin Tablet',
            'Heparin Injection',
            'Enoxaparin Injection',
            'Vitamin D3 Capsule',
            'Calcium Tablet',
            'Multivitamin Tablet',
            'Iron Tablet',
            'Folic Acid Tablet',
            'Vitamin B12 Injection',
            'Zinc Tablet',
            'ORS Sachet',
            'ORS Liquid',
            'Glucose Powder',
            'Insulin Regular',
            'Insulin NPH',
            'Insulin Glargine',
            'Thyroxine Tablet',
            'Carbimazole Tablet',
            'Prednisolone Tablet',
            'Dexamethasone Injection',
            'Hydrocortisone Injection',
            'Betamethasone Cream',
            'Clobetasol Cream',
            'Mometasone Cream',
            'Ketoconazole Cream',
            'Clotrimazole Cream',
            'Fluconazole Tablet',
            'Itraconazole Capsule',
            'Amphotericin Injection',
            'Acyclovir Tablet',
            'Valacyclovir Tablet',
            'Oseltamivir Capsule',
            'Remdesivir Injection',
            'Cough Syrup',
            'Antacid Syrup',
            'Digene Tablet',
            'Gelusil Syrup',
            'Loperamide Capsule',
            'ORS Powder',
            'Ranitidine Tablet',
            'Famotidine Tablet',
            'Sucralfate Syrup',
            'Lactulose Syrup',
            'Bisacodyl Tablet',
            'Senna Tablet',
            'Milk of Magnesia',
            'Albendazole Tablet',
            'Ivermectin Tablet',
            'Mebendazole Tablet',
            'Doxycycline Capsule',
            'Ciprofloxacin Tablet',
            'Levofloxacin Tablet',
            'Ofloxacin Tablet',
            'Tinidazole Tablet',
            'Metronidazole Tablet',
            'Chloroquine Tablet',
            'Artemisinin Combination Therapy',
            'Primaquine Tablet',
            'Anti Rabies Vaccine',
            'BCG Vaccine',
            'MMR Vaccine',
            'Polio Vaccine',
            'Hepatitis B Vaccine',
            'COVID-19 Vaccine',
            'Tetanus Toxoid Injection',
            'Vitamin C Tablet',
            'Magnesium Tablet',
            'Potassium Tablet',
            'Sodium Bicarbonate',
            'Calcium Gluconate Injection',
            'Diazepam Tablet',
            'Lorazepam Tablet',
            'Alprazolam Tablet',
            'Clonazepam Tablet',
            'Sertraline Tablet',
            'Fluoxetine Capsule',
            'Paroxetine Tablet',
            'Escitalopram Tablet',
            'Amitriptyline Tablet',
            'Olanzapine Tablet',
            'Risperidone Tablet',
            'Haloperidol Injection',
            'Phenytoin Capsule',
            'Carbamazepine Tablet',
            'Valproate Tablet',
            'Levetiracetam Tablet',
            'Topiramate Tablet',
            'Gabapentin Capsule',
            'Pregabalin Capsule',
            'Tramadol Capsule',
            'Morphine Injection',
            'Fentanyl Patch',
            'Codeine Syrup',
            'Hydrocodone Tablet',
            'Buprenorphine Tablet',
            'Naloxone Injection',
            'Ondansetron Injection',
            'Domperidone Syrup',
            'Metoclopramide Injection',
            'Prochlorperazine Tablet',
            'Promethazine Syrup',
            'Chlorpheniramine Tablet',
            'Loratadine Tablet',
            'Fexofenadine Tablet',
            'Levocetirizine Tablet',
            'Desloratadine Tablet',
            'Hydroxyzine Tablet',
            'Salbutamol Inhaler',
            'Formoterol Inhaler',
            'Budesonide Inhaler',
            'Fluticasone Inhaler',
            'Tiotropium Inhaler',
            'Ipratropium Nebulizer',
            'Montelukast Chewable',
            'Ambroxol Syrup',
            'Acetylcysteine Tablet',
            'Deriphylline Injection',
            'Theophylline Tablet',
            'Terbutaline Syrup',
            'Adrenaline Injection',
            'Dopamine Injection',
            'Noradrenaline Injection',
            'Atropine Injection',
            'Neostigmine Injection',
            'Glycopyrrolate Injection',
            'Midazolam Injection',
            'Propofol Injection',
            'Ketamine Injection',
            'Lidocaine Injection',
            'Bupivacaine Injection',
            'Ropivacaine Injection',
            'Oxytocin Injection',
            'Misoprostol Tablet',
            'Mifepristone Tablet',
            'Ethinyl Estradiol Tablet',
            'Levonorgestrel Tablet',
            'Oral Contraceptive Pills',
            'Clomiphene Tablet',
            'Human Chorionic Gonadotropin Injection',
            'Progesterone Injection',
            'Dydrogesterone Tablet',
            'Medroxyprogesterone Tablet',
            'Norethisterone Tablet',
            'Testosterone Injection',
            'Finasteride Tablet',
            'Dutasteride Capsule',
            'Tamsulosin Capsule',
            'Sildenafil Tablet',
            'Tadalafil Tablet',
            'Vardenafil Tablet',
            'Allopurinol Tablet',
            'Colchicine Tablet',
            'Febuxostat Tablet',
            'Indomethacin Capsule',
            'Naproxen Tablet',
            'Piroxicam Capsule',
            'Meloxicam Tablet',
            'Etoricoxib Tablet',
            'Celecoxib Capsule',
            'Vitamin K Injection',
            'Tranexamic Acid Tablet',
            'Tranexamic Acid Injection',
            'Ethamsylate Tablet',
            'Ethamsylate Injection',
            'Ferrous Sulfate Tablet',
            'Ferric Carboxymaltose Injection',
            'Iron Sucrose Injection',
            'Calcium Carbonate Tablet',
            'Calcitriol Capsule',
            'Alfacalcidol Capsule',
            'Zoledronic Acid Injection',
            'Alendronate Tablet',
            'Risedronate Tablet',
            'Denosumab Injection',
            'Insulin Aspart',
            'Insulin Lispro',
            'Insulin Detemir',
            'Insulin Degludec',
            'Glipizide Tablet',
            'Gliclazide Tablet',
            'Pioglitazone Tablet',
            'Vildagliptin Tablet',
            'Sitagliptin Tablet',
            'Linagliptin Tablet',
            'Empagliflozin Tablet',
            'Dapagliflozin Tablet',
            'Canagliflozin Tablet',
            'Acarbose Tablet',
            'Miglitol Tablet',
            'Repaglinide Tablet',
            'Nateglinide Tablet',
            'Glucagon Injection',
            'Hydroxychloroquine Tablet',
            'Azathioprine Tablet',
            'Methotrexate Tablet',
            'Cyclophosphamide Injection',
            'Mycophenolate Tablet',
            'Tacrolimus Capsule',
            'Cyclosporine Capsule',
            'Rituximab Injection',
            'Infliximab Injection',
            'Adalimumab Injection',
            'Etanercept Injection',
            'Interferon Injection',
            'Filgrastim Injection',
            'Pegfilgrastim Injection',
            'Epoetin Injection',
            'Darbepoetin Injection',
            'Thalidomide Capsule',
            'Lenalidomide Capsule',
            'Bortezomib Injection',
            'Imatinib Tablet',
            'Dasatinib Tablet',
            'Nilotinib Capsule',
            'Sorafenib Tablet',
            'Sunitinib Capsule',
            'Pazopanib Tablet',
            'Gefitinib Tablet',
            'Erlotinib Tablet',
            'Crizotinib Capsule',
            'Olaparib Tablet',
            'Bevacizumab Injection',
            'Trastuzumab Injection',
            'Cetuximab Injection',
            'Panitumumab Injection',
            'Nivolumab Injection',
            'Pembrolizumab Injection',
            'Atezolizumab Injection',
            'Durvalumab Injection',
            'Ipilimumab Injection',
        ];

        foreach ($medicineMaster as $name) {
            MedicineMaster::updateOrCreate(['name' => trim($name)]);
        }
    }
}
